### ISSUE TITLE
help shadows optix7

### ISSUE THREAD

**Issue by PerspectivesLab** [jbikker/lighthouse2#9] opened 2019-12-18 16:32 UTC
Hi!
i have imported a gltf file, but i am not able to cast the inner shadows, i have spend 2 days trying to figure out why, the renderer i use is "RenderCore_Optix7"
here is the screenshot:
![optix7](https://user-images.githubusercontent.com/25195799/71104028-72645380-21bb-11ea-8ff1-3598c445acfe.jpg)
my graphis card is a nvidia quadro p4000, with latest drivers and cuda 10.2

on the other hand i can cast inner shadows with renderer "RenderCore_OptixPrime_BDPT"
![notoptix](https://user-images.githubusercontent.com/25195799/71104308-e3a40680-21bb-11ea-899c-ca8772a4f2cc.jpg)

the gltf source file is here:
[scene.zip](https://github.com/jbikker/lighthouse2/files/3979428/scene.zip)

and it shows correctly with online gtlf view from 
https://pissang.github.io/clay-viewer/editor/
![wood1](https://user-images.githubusercontent.com/25195799/71104506-2e258300-21bc-11ea-97dd-f5af555046e5.jpg)

any idea what i am doing wrong there ? thx

**Comment by PerspectivesLab** [comment] 2019-12-19 15:19
ok i figured out ! i was applying a scale a root node level in the gltf file that was misleading the shadow calculations, the solution was to apply scale directly at vertex level, and then exporting to gltf

**Comment by PerspectivesLab** [comment] 2019-12-23 07:52
it seems while applying a scale to the model ( ex 0.5,0.5,0.5 ), that the source matrix calculation is causing incorrect results for shadows/shade/ambient:
in rendercore.cpp
```
			if (instance->transform)
			{
				T = mat4::Identity();
				memcpy( &T, instance->transform , 12* sizeof( float ) );
				invT = T.Inverted();  

			}
			else
			{
				T = mat4::Identity();
				invT = mat4::Identity();
			} 
```
if i use only:
```
				T = mat4::Identity();
				invT = mat4::Identity();
```
the shadows/ambient are working
could you comfirm you have the same behaviour with the gltf model provided ? with rendercore optix 7.0.
how can i make model transform scale work ? thx

**Comment by PerspectivesLab** [comment] 2019-12-23 17:18
ok i created a pull request for that, let me know if it goes through, thx

**Comment by jbikker** [comment] 2019-12-27 12:32
Sorry for the late reply, I missed your comment.
I think the issue is a bit deeper: when using a transform on instances the shading code must take this into account for normals by applying the same transform to these vectors. Or more accurately, to obtain corect transformed normals the inverse of the transpose of the transform must be applied. This is the same as the transform itself for orthonormal matrices, but scale matrices are not orthonormal...
I will fix this in the new year. In the meantime: the fix you proposed will not work if the model is rotated, but for now it should indeed solve your problem.

**Comment by jbikker** [comment] 2019-12-27 19:37
I have committed a couple of fixes that should resolve your problem. I will close the issue now; if it turns out your problem persists please reopen it.

**Closed as completed by jbikker** 2019-12-27 19:37 UTC
